description 'Protocol Library Html Protocol Formatter'


apply from: file('../gradle/javadoc.gradle')
apply from: file('../gradle/quality.gradle')
apply from: file('../gradle/publishing.gradle')


dependencies {
  implementation project(':protocol-core')

  compileOnly(libs.commons.text) { transitive = false }
  compileOnly(libs.guava) { transitive = false }
  compileOnly libs.owasp.encoder
  compileOnly(libs.spring.web) { transitive = false }
  compileOnly libs.unbescape

  testImplementation libs.guava
}
