/*
 * Copyright 2025 Jeroen Gremmen
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//file:noinspection DependencyNotationArgument


description = 'Protocol Library Html Protocol Formatter'


configurations {
  optionalApi

  compileOnlyApi.extendsFrom(optionalApi)
}


dependencies {
  implementation project(':protocol-core')

  optionalApi(libs.commons.text) { transitive = false }
  optionalApi(libs.guava) {
    exclude module: 'error_prone_annotations'
    exclude module: 'j2objc-annotations'
    exclude module: 'jspecify'
    exclude module: 'listenablefuture'
  }
  optionalApi libs.owasp.encoder
  optionalApi(libs.spring.web) { transitive = false }
  optionalApi libs.unbescape

  testImplementation libs.guava
}


publishOnCentral {
  projectDescription = 'HTML protocol formatter for rendering protocol entries as nested list structures with severity/depth CSS classes and optional Font Awesome icons'
}


publishing {
  publications {
    withType(MavenPublication).configureEach {
      pom {
        inceptionYear = '2025'

        url = "https://lib.sayayi.de/protocol/${releaseVersion}"

        withXml {
          def optionalArtifactIds = configurations.optionalApi
                  .resolvedConfiguration
                  .firstLevelModuleDependencies
                  .collect { it.moduleName }
                  .toSet()

          asNode().dependencies[0]?.dependency?.each { dependency ->
            if (dependency.artifactId.text() in optionalArtifactIds)
              dependency.appendNode('optional', 'true')
          }
        }
      }
    }
  }
}


ext.releaseTask.configure {
  if (snapshot)
    dependsOn ':protocol-html:publishOSSRHPublicationToMavenCentralSnapshotRepository'
}
