# CI script
image: openjdk:8-jdk-slim

stages:
  - build

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: ".gradle-cache"

before_script:
  - chmod +x ./gradlew

cache:
  paths:
    - .gradle-cache

build:
  stage: build
  script: ./gradlew clean build
  artifacts:
    paths:
      - ./build/libs/*
    expire_in: 4 weeks
