# CI script
image: localhost:5000/sayayi-jdk:17

stages:
  - build

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: ".gradle-cache"

before_script:
  - export JAVA_HOME="/usr/lib/jvm/jdk-17"
  - chmod +x ./gradlew

cache:
  paths:
    - .gradle-cache

build:
  stage: build
  tags:
    - docker
  script:
    - ./gradlew clean build
#    - ./gradlew docs
  artifacts:
    name: "protocol-artifacts"
    paths:
      - protocol-core/.build/libs/*.jar
      - protocol-message-matcher/.build/libs/*.jar
    expire_in: 2 weeks
