# CI script
image: java:8-jdk

stages:
  - build

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: ".gradle-cache"

before_script:
  - chmod +x ./gradlew

cache:
  paths:
    - .gradle-cache

build:
  stage: build
  script: ./gradlew clean build sonarqube -Dsonar.host.url="$SONAR_HOST_URL" -Dsonar.login="$SONAR_LOGIN" -Dsonar.projectKey="gitlab:protocol:$CI_COMMIT_REF_SLUG" --info
  artifacts:
    paths:
      - ./build/libs/*
    expire_in: 4 weeks
