# CI script
image: localhost:5000/sayayi-jdk:17

stages:
  - build

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: ".gradle"

before_script:
  - chmod +x ./gradlew

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  tags:
    - docker
  script: ./gradlew clean build
  artifacts:
    name: "protocol-artifacts"
    paths:
      - protocol-core/.build/libs/*.jar
      - protocol-message-matcher/.build/libs/*.jar
    expire_in: 2 weeks
